### ISSUE TITLE
Suggestion: move README in main page

### ISSUE THREAD

**Issue by lekkas** [balena-io/sshproxy#5]
This README is pretty sweet (https://github.com/resin-io/sshproxy/blob/master/resin/README.md),  it'd be great if we had it under the main folder (for a moment I thought documentation slipped through when transferring the repo, but it simply is one level deeper)

**Comment by wrboyce** [comment]
There is actually method in the madness here. The repository essentially contains two things, `sshproxy` the library and `sshproxy/resin` the binary. The README in the subfolder is only relevant to the `sshproxy/resin` binary, the documentation for using the `sshproxy` library is at https://godoc.org/github.com/resin-io/sshproxy which is linked to from the top-level README.

Have I managed to convince you it makes sense how it is?

**Comment by wrboyce** [comment]
I've been thinking about this some more and I think it actually makes sense to split this repository into *two* projects: `sshproxy` the library and `resin-sshproxy` the binary.

As it stands we have releases and versioning on this project which are mostly related to the `/resin` component; splitting the two off will allow for independent versioning and a clearer split in documentation and purpose.

**Comment by lekkas** [comment]
Hey, sorry I totally missed he first reply.

I agree that it'd probably make sense to separate any resin-specific logic to a separate module, but I think this is relatively low priority and not worth the effort to manage two separate projects, at least for now
